# documents/urls.py
"""
Documents app URLs using Django REST Framework's DefaultRouter.

This registers DocumentViewSet and automatically exposes:
  - /api/documents/          (list, create)
  - /api/documents/{id}/     (retrieve, update, partial_update, destroy)
  - /api/documents/search/   (custom action defined with @action(detail=False))
"""

from rest_framework.routers import DefaultRouter
from .views import DocumentViewSet

router = DefaultRouter()
# registers endpoints for the viewset under the 'documents' prefix
router.register(r'documents', DocumentViewSet, basename='documents')

# router.urls is a list of URL patterns generated by DRF
urlpatterns = router.urls


