# Generated by Django 5.2.5 on 2025-08-13 09:12

import documents.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=documents.models.upload_to_uploads,
                    ),
                ),
                ("fileName", models.CharField(blank=True, max_length=512)),
                ("creationDate", models.DateTimeField(auto_now_add=True)),
                ("data", models.TextField(blank=True)),
                ("fileSize", models.BigIntegerField(blank=True, null=True)),
                ("contentType", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-creationDate"],
            },
        ),
    ]
