# Generated by Django 5.2.5 on 2025-08-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["-creationDate"], "verbose_name": "Document"},
        ),
    ]
