# Generated by Django 5.2.5 on 2025-08-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_document_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-creationDate"],
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
    ]
