# Generated by Django 5.2.5 on 2025-08-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_document_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="document",
            table="document",
        ),
    ]
