# Generated by Django 5.2.5 on 2025-08-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_document_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="document",
            table=None,
        ),
    ]
