# Generated by Django 5.2.5 on 2025-08-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_alter_document_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="document",
            table="document",
        ),
    ]
